[package]
name = "mps-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.26.3" }
symphonia = { version = "0.4.0", optional = true, features = [
    "aac", "flac", "mp3", "pcm", "vorbis", "isomp4", "ogg", "wav"
] }
dirs = { version = "4.0.0", optional = true}

[features]
default = [ "music_library" ]
music_library = [ "symphonia", "dirs" ] # song metadata parsing and database auto-population
